updates

diff --git a/dx-scripts/build b/dx-scripts/build
--- a/dx-scripts/build
+++ b/dx-scripts/build
@@ -6,21 +6,68 @@ SCRIPT_DIR=$( cd -- "$( dirname -- "${0}" )" > /dev/null 2>&1 && pwd )
 
 . "${SCRIPT_DIR}/dx.sh.lib"
 
+read_custom_build_args() {
+  build_args_file="${SCRIPT_DIR}/build.args"
+  if [ -e "${build_args_file}" ]; then
+    for arg in `grep -v '^#' "${build_args_file}"`; do
+      BUILD_ARGS+=(--build-arg ${arg})
+    done
+  fi
+}
+
+setup_local_user_build_args() {
+  require_command "id"
+  require_command "uname"
+  user_uid=$(id -u)
+  user_gid=$(id -g)
+  docker_gid=
+  sadly_user_must_be_added_to_root=
+  OS=$(uname)
+  if [ "${OS}" == "Darwin" ] ; then
+    docker_gid=$(stat -f %g /var/run/docker.sock)
+    sadly_user_must_be_added_to_root="0,"
+  else
+    if [ "${OS}" == "Linux" ] ; then
+      docker_gid=$(stat -c %g /var/run/docker.sock)
+    else
+      log "Could not determine OS, which is needed to know how to invoke stat to figure out the group id of /var/run/docker.sock"
+      log "Docker commands will not work"
+    fi
+  fi
+  echo user_uid=${user_uid}                                                 >  "${SCRIPT_DIR}"/build.args
+  echo user_gid=${user_gid}                                                 >> "${SCRIPT_DIR}"/build.args
+  echo docker_gid=${docker_gid}                                             >> "${SCRIPT_DIR}"/build.args
+  echo sadly_user_must_be_added_to_root=${sadly_user_must_be_added_to_root} >> "${SCRIPT_DIR}"/build.args
+}
+
+
 require_command "docker"
 load_docker_compose_env
 
 usage_on_help "Builds the Docker image based on the Dockerfile" "" "build.pre" "build.post" "${@}"
 
-exec_hook_if_exists "build.pre" Dockerfile.dx "${IMAGE}"
+if ! exec_hook_if_exists "build.pre" Dockerfile.dx "${IMAGE}"; then
+  log "build.pre failed"
+  exit 1
+fi
+BUILD_ARGS=()
+
+setup_local_user_build_args
+read_custom_build_args
 
 docker build \
   --file Dockerfile.dx \
   --tag "${IMAGE}" \
+  ${BUILD_ARGS[@]} \
   ./
 
-exec_hook_if_exists "build.post" Dockerfile.dx "${IMAGE}"
+if ! exec_hook_if_exists "build.post" Dockerfile.dx "${IMAGE}"; then
+  log "build.pre failed"
+  exit 1
+fi
 
 log "🌈" "Your Docker image has been built tagged '${IMAGE}'"
 log "🔄" "You can now run dx/start to start it up, though you may need to stop it first with Ctrl-C"
 
 # vim: ft=bash
+
diff --git a/dx-scripts/exec b/dx-scripts/exec
--- a/dx-scripts/exec
+++ b/dx-scripts/exec
@@ -9,16 +9,24 @@ SCRIPT_DIR=$( cd -- "$( dirname -- "${0}" )" > /dev/null 2>&1 && pwd )
 require_command "docker"
 load_docker_compose_env
 
-usage_description="Execute a command inside the app's container."
-usage_args="[-s service] command"
+usage_description="Execute a command inside the app's container. Any command other than 'bash' will be run with bash -lc. Use -B to just run the command directly. Use -A to avoid ssh-agent."
+usage_args="[-s service] [-B] [-A] command"
 usage_pre="exec.pre"
 usage_on_help "${usage_description}" "${usage_args}" "${usage_pre}" "" "${@}"
 
 SERVICE="${SERVICE_NAME:-${DEFAULT_SERVICE}}"
-while getopts "s:" opt "${@}"; do
+INCLUDE_PREFIX_FOR_NON_BASH=true
+SSH_AGENT=true
+while getopts "s:AB" opt "${@}"; do
   case ${opt} in
     s )
       SERVICE="${OPTARG}"
+      ;;
+    A )
+      SSH_AGENT=false
+      ;;
+    B )
+      INCLUDE_PREFIX_FOR_NON_BASH=false
       ;;
     \? )
       log "🛑" "Unknown option: ${opt}"
@@ -37,10 +45,23 @@ if [ $# -eq 0 ]; then
   usage "${description}" "${usage_args}" "${usage_pre}"
 fi
 
+if ! exec_hook_if_exists "exec.pre"; then
+  log "build.pre failed"
+  exit 1
+fi
 
-exec_hook_if_exists "exec.pre"
+if [ "$#" -eq 1 ] && [ "$1" = "bash" ]; then
+  COMMAND=(bash)
+elif [ "$INCLUDE_PREFIX_FOR_NON_BASH" = "true" ]; then
+  COMMAND=(bash -lc "$*")
+else
+  COMMAND=("$@")
+fi
+if [ "$SSH_AGENT" = "true" ]; then
+  COMMAND=(ssh-agent "${COMMAND[@]}")
+fi
 
-log "🚂" "Running '${*}' inside container with service name '${SERVICE}'"
+log "🚂" "Running '${COMMAND[@]}' inside container with service name '${SERVICE}'"
 
 docker \
   compose \
@@ -49,6 +70,6 @@ docker \
     --env-file "${ENV_FILE}" \
   exec \
     "${SERVICE}" \
-    "${@}"
+    "${COMMAND[@]}"
 
 # vim: ft=bash
